### ISSUE TITLE
crontab fulfilled of ^@^@^@^@^@^@^@^@^@^@^@^@^@

### ISSUE THREAD

**Issue by matthieumarrast** [metwork-framework/mfext#1557]
metwork update from v2.0 to v2.1
```
service metwork stop
yum update metwork-mf*
service metwork start
```
start raises error:
```
*************************************
*****     STARTING MFSYSMON     *****
*************************************

- Generating circus.ini                                    [ OK ]
- Starting circus...                                       [ OK ]
- Waiting for circus daemon...                             [ OK ]
- Waiting for start of vector...                           [ OK ]
- Waiting for start of telegraf...                         [ OK ]
- Starting of telegraf_collector_custom_diskio             [ OK ]
- Starting of telegraf_collector_custom_netstat            [ OK ]
- Starting of telegraf_collector_custom_netio              [ OK ]
- Waiting for start of telegraf_collector_custom_dis[[..…  [ OK ]
- Waiting for start of telegraf_collector_custom_net[[..…  [ OK ]
- Waiting for start of telegraf_collector_custom_netio...  [ OK ]
- Waiting for start of telegraf...                         [ OK ]
- Waiting for start of telegraf_collector_metwork_mo[[..…  [ OK ]
- Building crontab file...                                 [ OK ]
- Installing crontab file...                               [ ERROR ] (can't install)
ERROR: see /home/mfsysmon/tmp/deploycron_errors.2145434 for details
=> you probably have a bad crontab in a plugin, try to remove them
   one by one and relaunch _make_and_install_crontab.sh after each removal
   to find which one
- Wait 2 sec...                                            [ OK ]
- Checking circus status...                                [ OK ]
- Checking crontab is not empty...                         [ ERROR ] (crontab is empty)
- Checking vector...                                       [ OK ]
- Checking telegraf_collector_custom_diskio...             [ OK ]
- Checking telegraf_collector_custom_netstat...            [ OK ]
- Checking telegraf_collector_custom_netio...              [ OK ]

ERROR(S) DETECTED DURING MFSYSMON CHECK
```

```
# cat /home/mfsysmon/tmp/deploycron_errors.2145434
Traceback (most recent call last):
  File "/opt/metwork-mfext-2.1/opt/python3/bin/deploycron_file", line 8, in <module>
    sys.exit(main())
  File "/opt/metwork-mfext-2.1/opt/python3/lib/python3.10/site-packages/deploycron/cli_deploycron_file.py", line 20, in main
    deploycron.deploycron(filename=filepath)
  File "/opt/metwork-mfext-2.1/opt/python3/lib/python3.10/site-packages/deploycron/__init__.py", line 42, in deploycron
    _install_content(installed_content)
  File "/opt/metwork-mfext-2.1/opt/python3/lib/python3.10/site-packages/deploycron/__init__.py", line 119, in _install_content
    raise ValueError("failed to install crontab, check if crontab is "
ValueError: failed to install crontab, check if crontab is valid ; out=b'' ; err=b'"-":1: bad minute\nerrors in crontab file, can\'t install.\n'
```

so I try the below command:
```
[mfsysmon@xxxxxx:~] $deploycron_file tmp/config_auto/crontab
Traceback (most recent call last):
  File "/opt/metwork-mfext-2.1/opt/python3/bin/deploycron_file", line 8, in <module>
    sys.exit(main())
  File "/opt/metwork-mfext-2.1/opt/python3/lib/python3.10/site-packages/deploycron/cli_deploycron_file.py", line 20, in main
    deploycron.deploycron(filename=filepath)
  File "/opt/metwork-mfext-2.1/opt/python3/lib/python3.10/site-packages/deploycron/__init__.py", line 42, in deploycron
    _install_content(installed_content)
  File "/opt/metwork-mfext-2.1/opt/python3/lib/python3.10/site-packages/deploycron/__init__.py", line 119, in _install_content
    raise ValueError("failed to install crontab, check if crontab is "
ValueError: failed to install crontab, check if crontab is valid ; out=b'' ; err=b'"-":1: bad minute\nerrors in crontab file, can\'t install.\n'
```
it reproduces the error.
but on another server with same crontab file I do not have the error.

**Comment by matthieumarrast** [comment]
```
[mfsysmon@xxxxxxxxxxx:~] $ crontab -e
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
```

**Comment by matthieumarrast** [comment]
fixed by removing crontab content with command `crontab -e` followed by module restart or execute `deploycron_file tmp/config_auto/crontab`

**Comment by thebaptiste** [comment]
May be something to do with https://github.com/metwork-framework/mfext/issues/1213

**Comment by matthieumarrast** [comment]
Yes maybe. It's not the first time I notice this issue. I think it can happen with other modules, not especially mfsysmon.
But hard to reproduce, so hard to fix.

**Comment by matthieumarrast** [comment]
Today I face this problem on mfserv.
I have updated the title of this issue.
We are not able to reproduce the way the crontab is fullfilled with "^@^@^@^@^@^@^@^@^@..."

**Comment by thebaptiste** [comment]
Issue transferred in mfext as it's not a specific mfsysmon issue

**Comment by matthieumarrast** [comment]
For two users (but not me) migrating from metwork **v2.1** to **v2.2**, the crontab was fullfiled of `^@^@^@^@...`, it is still very annoying.

**Comment by thebaptiste** [comment]
It's not sure that the problem is fixed as we didn't succeed to reproduce it.
Let's see if it occurs again in a next update...
