### ISSUE TITLE
django4 and psycopg

### ISSUE THREAD

**Issue by matthieumarrast** [metwork-framework/mfext#1674]
**Django 4** requires **psycopg** >= 3.1.8.

So as MetWork currently provides version 3.1.4, you can download the expected version of psycopg by updating the file `python3_virtualenv_sources/requirements-to-freeze.txt` in your plugin path, as below
```
django>=4
psycopg>=3.1.8
```

But it raises an error with `psycopg._cmodule`:
```
>>> import psycopg
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mfserv/var/plugins/django4/local/lib/python3.10/site-packages/psycopg/__init__.py", line 11, in <module>
    from . import postgres
  File "/home/mfserv/var/plugins/django4/local/lib/python3.10/site-packages/psycopg/postgres.py", line 9, in <module>
    from ._adapters_map import AdaptersMap
  File "/home/mfserv/var/plugins/django4/local/lib/python3.10/site-packages/psycopg/_adapters_map.py", line 14, in <module>
    from ._cmodule import _psycopg
  File "/home/mfserv/var/plugins/django4/local/lib/python3.10/site-packages/psycopg/_cmodule.py", line 16, in <module>
    from psycopg_c import _psycopg as _psycopg
  File "psycopg_c/_psycopg/generators.pyx", line 14, in init psycopg_c._psycopg
  File "/home/mfserv/var/plugins/django4/local/lib/python3.10/site-packages/psycopg/waiting.py", line 22, in <module>
    from ._cmodule import _psycopg
ImportError: cannot import name '_psycopg' from partially initialized module 'psycopg._cmodule' (most likely due to a circular import) (/home/mfserv/var/plugins/django4/local/lib/python3.10/site-packages/psycopg/_cmodule.py)
```

I think this is because the version of `psycopg_c` used is the one provided in directory `/opt/metwork-mfext-2.1/opt/python3_scientific_core/lib/python3.10/site-packages` (present in plugin PYTHONPATH), so the v3.1.4:
```
drwxr-xr-x. 6 root root 4096 18 sept. 17:53 psycopg
drwxr-xr-x. 3 root root 4096 18 sept. 17:53 psycopg2
drwxr-xr-x. 2 root root  119 18 sept. 17:53 psycopg2-2.9.3.dist-info
drwxr-xr-x. 2 root root  123 18 sept. 17:53 psycopg-3.1.4.dist-info
drwxr-xr-x. 5 root root 4096 18 sept. 17:53 psycopg_c
drwxr-xr-x. 2 root root  123 18 sept. 17:53 psycopg_c-3.1.4.dist-info
```

As a **workaround**, you must add **psycopg_c** in your plugin's requirement file:
```
django>=4
psycopg_c>=3.1.8
psycopg>=3.1.8
```

Waiting for more recent version of psycopg in next metwork release, I don't know if there is another solution !?
why psycopg 3.1.8 did not download related psycopg_c library ? because present in pythonpath ? ...

**Comment by matthieumarrast** [comment]
much better
```
psycopg[c]>=3.1.8
```
