### ISSUE TITLE
inject_file fails because missing env. variable MFDATA_INTERNAL_PLUGINS_LISTENED_DIRECTORIES

### ISSUE THREAD

**Issue by dearith** [metwork-framework/mfext#940]
With MetWork 1.0, inject_file fails because MFDATA_INTERNAL_PLUGINS_LISTENED_DIRECTORIES is missing:

```
Traceback (most recent call last):
  File "/opt/metwork-mfext-1.0/opt/python3/bin/inject_file", line 11, in <module>
    sys.exit(main())
  File "/opt/metwork-mfext-1.0/opt/python3/lib/python3.7/site-packages/acquisition/inject_file.py", line 48, in main
    first_directory = os.environ[env_var].split(',')[0]
  File "/opt/metwork-mfext-1.0/opt/python3_core/lib/python3.7/os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'MFDATA_INTERNAL_PLUGINS_LISTENED_DIRECTORIES'
```
According to the MFDATA_INTERNAL_* variables, i think the correct variable should be MFDATA_INTERNAL_PLUGINS_WATCHED_DIRECTORIES

**Comment by dearith** [comment]
Workaround while waiting for the fix : before using inject_file : define MFDATA_INTERNAL_PLUGINS_LISTENED_DIRECTORIES
`export MFDATA_INTERNAL_PLUGINS_LISTENED_DIRECTORIES=$MFDATA_INTERNAL_PLUGINS_WATCHED_DIRECTORIES`
